Add read me
ConfusedSatlan/online-book-store pull request #14
Opened 2023-10-01 18:07 UTC by ConfusedSatlan

2023-10-05 12:40 UTC, andrii-hoienko requested changes
Please read and follow the hints

2023-10-05 12:40 UTC, andrii-hoienko commented on README.md
> +- A working development environment with your preferred programming language and tools.
what tools? what language?

2023-10-05 12:40 UTC, andrii-hoienko commented on README.md
> +### Installation
Add alternative way to run app

2023-10-05 12:40 UTC, andrii-hoienko commented on README.md
> +Before you begin, ensure you have the following prerequisites:
Mention the specific functionalities of your controllers.

2023-10-05 12:40 UTC, andrii-hoienko commented on README.md
> +Configuration options for the Bookstore API are stored in the `.env` file. You can customize settings such as production and debugging ports by editing this file.
Add something about Contribution

2023-10-05 12:40 UTC, andrii-hoienko commented on README.md
> +POSTGRES_DOCKER_PORT=5432
Detail the technologies and tools used, like Spring Boot, Spring Security, Spring Data JPA, Swagger, etc.

2023-10-16 15:05 UTC, vovasalyha requested changes
GJ, let's improve few more things

2023-10-16 15:05 UTC, vovasalyha commented on README.md
> +- **Docker:** Proficiency in using Docker for containerization to package and run your application.
proficiency in Docker is not required for such a trivial setup. User should be able to run your app without deep knowledge of Docker simply using the commands from your guide

2023-10-16 15:05 UTC, vovasalyha commented on README.md
> +   ```bash
please, close the code blocks with tracing ```

2023-10-16 15:05 UTC, vovasalyha commented on README.md
> +bash
make it a code block

2023-10-16 15:05 UTC, vovasalyha commented on README.md
> +bash
make it a code block

2023-10-18 11:49 UTC, andrii-hoienko approved these changes
GJ!

2023-10-19 06:32 UTC, merged