Crate model, service, repository, connection with prop
ConfusedSatlan/online-book-store pull request #2
Opened 2023-08-29 16:44 UTC by ConfusedSatlan

2023-08-29 16:59 UTC, Denis-Balako requested changes
Good job! Let's improve it!

2023-08-29 16:59 UTC, Denis-Balako commented on pom.xml
> +		<dependency>
Make your dependency list more fancy - delete redundant lines 😃

2023-08-29 16:59 UTC, Denis-Balako commented on src/main/java/application/onlinebookstore/OnlineBookStoreApplication.java
> +    private BookService bookService;
Don't forget about dependency injection - provide this service through constructor and add @ Autowired above constructor.

2023-08-29 16:59 UTC, Denis-Balako commented on src/main/java/application/onlinebookstore/model/Book.java
> +    private BigDecimal price;
These fields should be not null and isbn should be unique.

2023-08-29 16:59 UTC, Denis-Balako commented on src/main/java/application/onlinebookstore/model/Book.java
> +    private String coverImage;
Check the column name in DB. It responds to naming conventions?

2023-08-29 16:59 UTC, Denis-Balako commented on src/main/java/application/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +                    "SELECT b FROM Book b", Book.class).getResultList();
```suggestion
                    "FROM Book", Book.class).getResultList();
```

2023-08-29 16:59 UTC, Denis-Balako commented on src/main/java/application/onlinebookstore/service/BookService.java
> +
Redundant line

2023-08-30 09:10 UTC, Denis-Balako requested changes
Fix minor issues

2023-08-30 09:10 UTC, Denis-Balako commented on src/main/java/application/onlinebookstore/model/Book.java
> +    private String isbn;
```suggestion
    @Column(nullable = false, unique = true, name = "isbn")
    private String isbn;
```

2023-08-30 09:10 UTC, Denis-Balako commented on src/main/java/application/onlinebookstore/model/Book.java
> +    private String coverImage;
https://medium.com/@centizennationwide/mysql-naming-conventions-e3a6f6219efe

```suggestion
    @Column(name = "cover_image")
    private String coverImage;
```

2023-08-30 10:08 UTC, Denis-Balako approved these changes
Great job!

2023-09-01 09:26 UTC, Vasul-Pankiv approved these changes

2023-09-01 09:26 UTC, Vasul-Pankiv commented on pom.xml
> +
empty line

2023-09-01 15:34 UTC, merged