Create controller, dto, MapperConfig
ConfusedSatlan/online-book-store pull request #3
Opened 2023-09-02 09:10 UTC by ConfusedSatlan

2023-09-02 14:43 UTC, Dimagaa requested changes
Looks good)

2023-09-02 14:43 UTC, Dimagaa commented on src/main/java/application/onlinebookstore/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping(value = "/api/books")

```

2023-09-02 14:43 UTC, Dimagaa commented on src/main/java/application/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Can't insert book " + book, e);
I think the previous exception was more appropriate =)

2023-09-02 14:43 UTC, Dimagaa commented on src/main/java/application/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +    public Book findByTitle(String title) {
It is better to return Optional, there is a method for this purpose.

2023-09-02 14:43 UTC, Dimagaa commented on src/main/java/application/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +        } catch (Exception e) {
the same:
1. Optional.ofNullable()
2. Here use Session.get() method instead of creation query.

2023-09-02 14:43 UTC, Dimagaa commented on src/main/java/application/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.findById(id));
Here you should throw an exception if there is no book for the provided ID

2023-09-02 14:43 UTC, Dimagaa commented on src/main/java/application/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.findByTitle(title));
the same as above

2023-09-03 14:46 UTC, Someboty approved these changes
Looks great!

2023-09-04 15:03 UTC, vovasalyha requested changes
GJ! Let's improve it a bit.

2023-09-04 15:03 UTC, vovasalyha commented on pom.xml
> +			<artifactId>spring-boot-starter</artifactId>
Why do you need this dependency?

2023-09-04 15:03 UTC, vovasalyha commented on src/main/java/application/onlinebookstore/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
You can use records for DTOs

2023-09-04 15:03 UTC, vovasalyha commented on src/main/java/application/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            return Optional.of(session.get(Book.class, title));
`Optional.of` throws NPE, check the docs. It's not what you want. Give the opportunity to decide whether to throw or not to the user of this class.

2023-09-04 15:03 UTC, vovasalyha commented on src/main/java/application/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            return Optional.of(session.get(Book.class, id));
Same here.

2023-09-05 12:46 UTC, Vasul-Pankiv approved these changes

2023-09-05 14:38 UTC, merged