Impl data jpa
ConfusedSatlan/online-book-store pull request #4
Opened 2023-09-04 16:03 UTC by ConfusedSatlan

2023-09-05 18:07 UTC, keda-vlad requested changes

2023-09-05 18:07 UTC, keda-vlad commented on src/main/java/application/onlinebookstore/repository/book/spec/AuthorSpecificationProvider.java
> +public class AuthorSpecificationProvider implements SpecificationProvider<Book> {
U need annotate this for creating bean

2023-09-05 18:07 UTC, keda-vlad commented on src/main/java/application/onlinebookstore/repository/book/spec/TitleSpecificationProvider.java
> +public class TitleSpecificationProvider implements SpecificationProvider<Book> {
U need annotate this for creating bean

2023-09-05 18:07 UTC, keda-vlad commented on src/main/java/application/onlinebookstore/consthelper/ArraysConst.java
> +}
Why do u need this?

2023-09-05 18:07 UTC, keda-vlad commented on src/main/java/application/onlinebookstore/controller/BookController.java
> +    private final BookService bookService;
Book Endpoints:

GET: /api/books (Retrieve book catalog) (should be done in the previous PR)
GET: /api/books/{id} (Retrieve book details) (should be done in the previous PR)
POST: /api/books (Create a new book) (should be done in the previous PR)
PUT: /api/books/{id} (Update a specific book) <----------------------------------------- U miss this

2023-09-05 18:07 UTC, keda-vlad commented on src/main/java/application/onlinebookstore/repository/book/impl/BookSpecificationBuilder.java
> +                    .getSpecificationProvider("title")
It`s better to make constant for this, and in all same case

2023-09-05 18:07 UTC, keda-vlad commented on src/main/java/application/onlinebookstore/repository/book/spec/AuthorSpecificationProvider.java
> +        return (root, query, criteriaBuilder) -> root.get("author")
It`s better to make constant for this, and in all same case

2023-09-06 08:30 UTC, keda-vlad approved these changes

2023-09-08 14:24 UTC, vovasalyha requested changes
Good. Please take a look on my comments.

2023-09-08 14:24 UTC, vovasalyha commented on src/main/java/application/onlinebookstore/service/impl/BookServiceImpl.java
> +    public List<BookDto> getBookByTitle(String title) {
Method is called getBook... but you actually returning a list, seems confusing. Whether call it getBooks... or return a single book.

2023-09-08 14:24 UTC, vovasalyha commented on src/main/java/application/onlinebookstore/service/impl/BookServiceImpl.java
> +        if (allByTitleContainsIgnoreCase.isEmpty()) {
if returning a list you don't need to throw an exception if it's empty, returning an empty list is OK

2023-09-08 14:24 UTC, vovasalyha commented on src/main/java/application/onlinebookstore/service/impl/BookServiceImpl.java
> +    public List<BookDto> getBookByAuthor(String author) {
the same as for title

2023-09-11 10:26 UTC, Vasul-Pankiv approved these changes

2023-09-13 14:58 UTC, merged