Create spring security
ConfusedSatlan/online-book-store pull request #9
Opened 2023-09-13 14:54 UTC by ConfusedSatlan

2023-09-14 07:21 UTC, Zel1oy approved these changes
GJ

2023-09-14 07:21 UTC, Zel1oy commented on src/main/java/application/onlinebookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto request) {
Add @Valid

2023-09-14 07:21 UTC, Zel1oy commented on src/main/java/application/onlinebookstore/mapper/UserMapper.java
> +public interface UserMapper {
I think you should add more methods like toModel, toDto

2023-09-14 08:02 UTC, nacenik requested changes
Good solution, let's improve it :)

2023-09-14 08:02 UTC, nacenik commented on src/main/java/application/onlinebookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto request) {
Not fixed. Dto won't be validated without this annotation

2023-09-14 08:02 UTC, nacenik commented on src/main/java/application/onlinebookstore/controller/BookController.java
> +    public List<BookDto> getAll(Authentication authentication, Pageable pageable) {
do you really need this parameter?

2023-09-14 08:02 UTC, nacenik commented on src/main/java/application/onlinebookstore/dto/user/UserLoginResponseDto.java
> +public class UserLoginResponseDto {
if you start using features from the newer version (records, etc.), please, use them everywhere (if it possible)

2023-09-14 08:02 UTC, nacenik commented on src/main/java/application/onlinebookstore/mapper/UserMapper.java
> +public interface UserMapper {
agree. Not fixed

2023-09-14 08:02 UTC, nacenik commented on src/main/java/application/onlinebookstore/model/User.java
> +    private Set<Role> roles;
Do you need this field in toString, equals, and hashcode?

2023-09-14 08:02 UTC, nacenik commented on src/main/java/application/onlinebookstore/repository/user/UserRepository.java
> +    @Query("FROM User u LEFT JOIN u.roles where u.email = :email")
your method should work even without hardcode the query.

2023-09-14 08:02 UTC, nacenik commented on src/main/java/application/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
create constant for this value

2023-09-14 08:02 UTC, nacenik commented on src/main/java/application/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
create constant for `"Bearer "` and instead of hardcode int, just call String method `.length() `

2023-09-14 08:02 UTC, nacenik commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +      author: bookstore
author is bookstore?

2023-09-15 12:17 UTC, andrii-hoienko requested changes
Nice, I left minor comments

2023-09-15 12:17 UTC, andrii-hoienko commented on src/main/java/application/onlinebookstore/mapper/UserMapper.java
> +    UserResponseDto toUserResponse(User user);
```suggestion
    UserResponseDto toUserResponseDto(User user);

```

2023-09-15 12:17 UTC, andrii-hoienko commented on src/main/java/application/onlinebookstore/security/JwtAuthenticationFilter.java
> +    private static final String HEADER_NAME_LOGIN = "Authorization";
```suggestion
    private static final String AUTHORIZATION/AUTHORIZATION_HEADER= "Authorization";

```

2023-09-15 12:17 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +      author: nikita
What if there are more than 1 nikita in team?

2023-09-15 12:17 UTC, andrii-hoienko commented on src/main/java/application/onlinebookstore/dto/user/UserLoginRequestDto.java
> +                                  @NotNull
In password annotation you already perform null case check

2023-09-15 12:17 UTC, andrii-hoienko commented on src/main/java/application/onlinebookstore/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("User is already registered!");
add some details to error message

2023-09-15 12:17 UTC, andrii-hoienko commented on src/main/java/application/onlinebookstore/service/impl/UserServiceImpl.java
> +        user.setRoles(Set.of(roleRepository.findByName(Role.RoleName.ROLE_USER).orElseThrow(
Please separate retrieving role from db and setting retrieved value for better readability

2023-09-15 12:17 UTC, andrii-hoienko commented on src/main/java/application/onlinebookstore/validation/impl/PasswordValidator.java
> +    private static final String PATTERN_OF_PASSWORD = "^(?=.*[A-Za-z])(?=.*\\d).{6,}$";
```suggestion
    private static final String PASSWORD_PATTERN = "^(?=.*[A-Za-z])(?=.*\\d).{6,}$";

```

2023-09-18 13:57 UTC, andrii-hoienko requested changes
Nice, I left minor comments

2023-09-18 13:57 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +      author: team
I mean that by author field your colleagues should identify the author of changes. As far as I know you name is not team, so please make author Mykyta Zuber

2023-09-18 13:57 UTC, andrii-hoienko commented on src/main/java/application/onlinebookstore/dto/user/UserLoginRequestDto.java
> +                                  @NotNull
not resolved

2023-09-19 15:18 UTC, vovasalyha approved these changes

2023-09-20 09:32 UTC, merged